### ISSUE TITLE
unable to install emcache on alpine linux

### ISSUE THREAD

**Issue by duxing** [pfreixes/emcache#40]
hi @pfreixes 

amazing work on `emcache`!
I'm setting up a python project with `emcache` but it seems like I can't install `emcache` on `alpine`
version of `emcache`: `0.3.0b0`

to reproduce: (need `docker` installed)
```
# launch an alpine linux container
docker run -it --rm python:3-alpine /bin/sh
# try installing in the container console
pip install --upgrade -v emcache
```

error message:
> Collecting emcache
>   ERROR: Could not find a version that satisfies the requirement emcache (from versions: none)
> ERROR: No matching distribution found for emcache

while on the other hand, using a different linux OS works:
```
docker run -it --rm python:3-slim-buster /bin/sh
pip install --upgrade -v emcache
```
which gives me:
> Installing collected packages: emcache
> Successfully installed emcache-0.3.0b0

seems like `manylinux` does wheel doesn't work with `musl` based distributions like `alpine` ([reference](https://github.com/pypa/manylinux/issues/37)) and I was wondering if it's a lot of work for you to build a package for `alpine`. it's the go-to option for containers and I believe it will make `emcache` easier to adopt.

Thanks in advance!

**Comment by pfreixes** [comment]
Sorry for the late response.

Yes, definitely Emcache should provide a wheel for alpine Linux, but seems that there is no easy way of doing this since for now many Linux - as you already mentioned - is not supporting `alipine`. 

We could try to provide a source package and make the compilation at installation time, but this would require to have all of the dependencies in place, which is always a good source of frustrations.

So, the options that we could have on the table right now would be:
- Wait and see until `alpine` is supported by the Manylinux project
- Publish a none binary package, which should allow the user to compile the Cython code at installation time
- Something that could I be missing

I would be inclined to know for doing a wait and see, unless someone believes that this is really critical.

WDYT?

**Comment by duxing** [comment]
thanks for getting back to me.

agreed. the best solution (if I were you) would be to wait for `manylinux` to support `alpine`. 

I'm familiar with the publishing process but I can easily see this being a PITA to do, and the outcome would be worthless once `alpine` is supposed by `manylinux` natively.

this is more of a "goo-to-have" or raise awareness issue. I've been getting around by using debian and the image size is not much bigger than `alpine`.
